const catalogue=require('./readCatalogue.json');
const {normalizeReferrerName}=require('./labRules.cjs');
function object(input,keys){if(!input || typeof input!=='object' || Array.isArray(input) || Object.keys(input).some(k=>!keys.includes(k)))throw new Error('Invalid operation fields');return input;}
function id(value){if(!Number.isSafeInteger(value) || value<=0)throw new Error('Invalid record identity');return value;}
function text(value,max=1000,required=false){if(value==null && !required)return null;if(typeof value!=='string' || value.length>max || (required && !value.trim()))throw new Error('Invalid text value');return value.trim() || null;}
function number(value,min=0,max=Number.MAX_SAFE_INTEGER){if(typeof value!=='number' || !Number.isFinite(value) || value<min || value>max)throw new Error('Invalid finite numeric value');return value;}
function dates(filters){object(filters,['dateFrom','dateTo']);for(const key of ['dateFrom','dateTo'])if(filters[key]!=null && filters[key]!=='' && (typeof filters[key]!=='string' || !/^\d{4}-\d{2}-\d{2}$/.test(filters[key])))throw new Error('Invalid date filter');return filters;}
function read(db,name,args=[]){
 if(typeof name!=='string')throw new Error('Unknown read operation');
 if(name==='catalogue.formulas'){if(!Array.isArray(args)||args.length)throw new Error('Invalid formula read');const tests=db.all('SELECT * FROM parameters');return db.all('SELECT parameter_id,formula_expression,dependencies FROM formulas').map(f=>{try{require('./formulaProvenance.cjs').capture(tests.find(t=>t.id===f.parameter_id),f,tests);return {...f,units_valid:true};}catch{return {...f,units_valid:false};}});}
 if(name==='reports.orders' || name==='results.pendingOrders'){
  const filters=dates(args),params=[];let sql=name==='reports.orders'?`SELECT o.*,p.patient_id AS pt_id,p.name AS patient_name,p.age,p.sex,p.phone,p.address,p.referred_by FROM orders o JOIN patients p ON o.patient_id=p.id WHERE 1=1`:`SELECT o.id,o.order_date,o.status,p.patient_id,p.name AS patient_name,p.referred_by FROM orders o JOIN patients p ON o.patient_id=p.id WHERE o.status IN ('pending','partial')`;
  if(filters.dateFrom){sql+=' AND date(o.order_date)>=?';params.push(filters.dateFrom);}if(filters.dateTo){sql+=' AND date(o.order_date)<=?';params.push(filters.dateTo);}
  sql+=name==='reports.orders'?' ORDER BY o.created_at DESC LIMIT 200':' ORDER BY o.order_date DESC,o.id DESC';return db.all(sql,params);
 }
 if(name==='referrals.invoiceTests'){if(!Array.isArray(args) || !args.length || args.length>1000)throw new Error('Provide 1–1000 order identities');args.forEach(id);return db.all(`SELECT ot.order_id,pr.name AS test_name,ot.display_order FROM order_tests ot JOIN parameters pr ON pr.id=ot.parameter_id WHERE ot.order_id IN (${args.map(()=>'?').join(',')}) ORDER BY ot.order_id,ot.display_order`,args);}
 if(!Object.hasOwn(catalogue,name))throw new Error('Unknown read operation');const query=catalogue[name];
 if(!Array.isArray(args) || args.length!==(query.sql.match(/\?/g)||[]).length || args.some(v=>v!==null && !(typeof v==='string' && v.length<=2000) && !(typeof v==='number' && Number.isFinite(v))))throw new Error('Invalid read arguments');
 return db[query.mode](query.sql,args);
}
function audit(db,user,action,recordId=null,metadata={}){db.db.run('INSERT INTO audit_log(table_name,record_id,action,new_value,changed_by) VALUES(?,?,?,?,?)',['application_security',recordId,action,JSON.stringify(metadata),user.username]);}
function atomic(db,fn){return db._referenceAtomic(()=>{const previous=db._initializing;db._initializing=true;try{return fn();}finally{db._initializing=previous;}});}
function registerPatientOrder(db,user,input){
 const p=object(input,['name','age','sex','phone','address','referred_by','tests','orderDate','requestId']);const name=text(p.name,200,true),age=p.age==null?null:number(p.age,0),sex=p.sex==null?null:text(p.sex,20);
 if(![null,'male','female','unknown','other',''].includes(sex))throw new Error('Invalid sex');const phone=text(p.phone,100),address=text(p.address,1000),ref=normalizeReferrerName(text(p.referred_by,200));dates({dateFrom:p.orderDate});if(!p.orderDate)throw new Error('Order date is required');
 if(!Array.isArray(p.tests) || !p.tests.length || p.tests.length>1000 || new Set(p.tests).size!==p.tests.length)throw new Error('Select unique ordered tests');p.tests.forEach(test=>{id(test);if(!db.get('SELECT id FROM parameters WHERE id=?',[test]))throw new Error('Unknown ordered parameter');});
 const actor=db._referenceActor(user),crypto=require('crypto'),requestId=p.requestId??crypto.randomUUID();if(typeof requestId!=='string'||! /^[a-f0-9-]{36}$/i.test(requestId))throw new Error('Invalid registration request identity');const requestHash=crypto.createHash('sha256').update(JSON.stringify([name,age,sex,phone,address,ref,p.tests,p.orderDate])).digest('hex');
 return atomic(db,()=>{const previous=db.get('SELECT * FROM registration_requests WHERE request_id=?',[requestId]);if(previous){if(previous.actor_id!==actor.id)throw new Error('Registration request belongs to a different operator');if(previous.request_hash!==requestHash)throw new Error('This submission already saved order #'+previous.order_id+' with different details. Review that order before creating another registration.');return {orderId:previous.order_id,patientId:previous.patient_id};}const patientId=db.constructor.getNextPatientId(db);db.run('INSERT INTO patients(patient_id,name,age,sex,phone,address,referred_by) VALUES(?,?,?,?,?,?,?)',[patientId,name,age,sex,phone,address,ref]);const patient=db.get('SELECT last_insert_rowid() AS id').id;db.run("INSERT INTO orders(patient_id,referring_doctor,order_date,status) VALUES(?,?,?,'pending')",[patient,ref,p.orderDate]);const orderId=db.get('SELECT last_insert_rowid() AS id').id;p.tests.forEach((test,i)=>db.run('INSERT INTO order_tests(order_id,parameter_id,display_order) VALUES(?,?,?)',[orderId,test,i+1]));db.computeOrderBillAndCommission(orderId);require('./billingLedger.cjs').initializeAccount(db,orderId,{legacy:false,actor:user});db.db.run('INSERT INTO registration_requests VALUES(?,?,?,?,?,?)',[requestId,actor.id,requestHash,orderId,patientId,new Date().toISOString()]);audit(db,actor,'register-order',orderId,{testCount:p.tests.length});return {orderId,patientId};});
}
function setPaymentStatus(db,user,orderId,status){
 id(orderId);if(!['paid','unpaid'].includes(status))throw new Error('Invalid payment update');
 return atomic(db,()=>{const ledger=require('./billingLedger.cjs'),money=require('./money.cjs');ledger.initializeAccount(db,orderId,{legacy:true});const account=ledger.getAccount(db,user,orderId);if(status==='unpaid'){if(account.balance_minor>0)return {ok:true};throw new Error('Use an authorized refund or reversal with a reason; posted payments cannot be erased');}if(account.balance_minor<=0){const before=db.get('SELECT payment_status FROM orders WHERE id=?',[orderId]).payment_status;if(before!=='paid'){db.db.run("UPDATE orders SET payment_status='paid' WHERE id=?",[orderId]);audit(db,db._referenceActor(user),'zero-outstanding-confirmed',orderId,{before,after:'paid'});}return {ok:true};}ledger.postEvent(db,user,{orderId,kind:'payment',amount:money.formatMoney(account.balance_minor),requestId:'legacy-paid-'+orderId+'-'+require('crypto').createHash('sha256').update(account.events.map(e=>e.id).join('|')).digest('hex').slice(0,32),reason:'Marked paid',method:'unspecified'});return {ok:true};});
}
function setRates(db,user,rows){if(!Array.isArray(rows) || rows.length>1000 || new Set(rows.map(r=>r.parameterId)).size!==rows.length)throw new Error('Invalid rate changes');rows.forEach(r=>{object(r,['parameterId','rate']);id(r.parameterId);number(r.rate);require('./money.cjs').toLegacyAmount(require('./money.cjs').parseMoney(String(r.rate)));if(!db.get("SELECT id FROM parameters WHERE id=? AND type!='derived'",[r.parameterId]))throw new Error('Invalid rate parameter');});return atomic(db,()=>{const before=rows.map(r=>({parameterId:r.parameterId,rate:db.get('SELECT rate FROM test_rates WHERE parameter_id=?',[r.parameterId])?.rate ?? null}));rows.forEach(r=>db.run('INSERT INTO test_rates(parameter_id,rate,updated_at) VALUES(?,?,datetime("now")) ON CONFLICT(parameter_id) DO UPDATE SET rate=excluded.rate,updated_at=excluded.updated_at',[r.parameterId,r.rate]));audit(db,user,'configure-rates',null,{before,after:rows});return {ok:true};});}
function setCommissions(db,user,input){const p=object(input,['defaultPercent','entries']);if(p.defaultPercent!==undefined)number(p.defaultPercent,0,100);if(!Array.isArray(p.entries) || p.entries.length>1000)throw new Error('Invalid commission entries');const entries=p.entries.map(r=>{object(r,['name','percent']);return {name:text(r.name,200,true),percent:number(r.percent,0,100)};});if(new Set(entries.map(r=>r.name)).size!==entries.length)throw new Error('Duplicate commission entry');return atomic(db,()=>{const beforeDefault=db.get('SELECT commission_default_percent AS n FROM lab WHERE id=1').n;if(p.defaultPercent!==undefined)db.run('UPDATE lab SET commission_default_percent=? WHERE id=1',[p.defaultPercent]);entries.forEach(r=>db.run('INSERT INTO referrer_commission_pct(referrer_name,commission_percent,updated_at) VALUES(?,?,datetime("now")) ON CONFLICT(referrer_name) DO UPDATE SET commission_percent=excluded.commission_percent,updated_at=excluded.updated_at',[r.name,r.percent]));audit(db,user,'configure-commissions',null,{beforeDefault,afterDefault:p.defaultPercent ?? beforeDefault,entryCount:entries.length});return {ok:true};});}
module.exports={read,audit,atomic,registerPatientOrder,setPaymentStatus,setRates,setCommissions,id,text,object};
