const fs=require('fs'),crypto=require('crypto');
const MAGIC=Buffer.from('LABBAK02');
function passphrase(p){if(typeof p!=='string'||p.length<12||p.length>1024)throw new Error('Backup passphrase must contain 12–1024 characters.');}
function encrypt(bytes,p){passphrase(p);const salt=crypto.randomBytes(16),iv=crypto.randomBytes(12),header=Buffer.concat([MAGIC,salt,iv]);const cipher=crypto.createCipheriv('aes-256-gcm',crypto.scryptSync(p,salt,32,require('./credentials.cjs').KDF),iv);cipher.setAAD(header);return Buffer.concat([header,cipher.update(bytes),cipher.final(),cipher.getAuthTag()]);}
function decrypt(bytes,p){passphrase(p);if(bytes.length<53||!bytes.subarray(0,8).equals(MAGIC))throw new Error('Unsupported backup format. Legacy backups require separate offline review.');try{const decipher=crypto.createDecipheriv('aes-256-gcm',crypto.scryptSync(p,bytes.subarray(8,24),32,require('./credentials.cjs').KDF),bytes.subarray(24,36));decipher.setAAD(bytes.subarray(0,36));decipher.setAuthTag(bytes.subarray(-16));return Buffer.concat([decipher.update(bytes.subarray(36,-16)),decipher.final()]);}catch{throw new Error('Backup authentication failed: wrong passphrase, damage or tampering.');}}
function replace(dest,bytes){const temp=dest+'.'+crypto.randomUUID()+'.tmp';try{const fd=fs.openSync(temp,'wx',0o600);try{fs.writeFileSync(fd,bytes);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}if(!fs.readFileSync(temp).equals(bytes))throw new Error('Snapshot verification failed');fs.renameSync(temp,dest);}finally{if(fs.existsSync(temp))fs.unlinkSync(temp);}}
function inspect(SQL,bytes,{current=false,expected=null}={}){const requireAdmin=current;bytes=Buffer.from(bytes);if(bytes.length<100||bytes.subarray(0,16).toString()!=='SQLite format 3\0')throw new Error('Database is empty or corrupt. Original file was preserved.');const db=new SQL.Database(bytes);try{if(db.exec('PRAGMA integrity_check')[0]?.values[0][0]!=='ok')throw new Error('Database integrity check failed');const tables=new Set(db.exec("SELECT name FROM sqlite_master WHERE type='table'")[0]?.values.map(r=>r[0]));for(const t of ['lab','parameters','patients','orders','order_tests','order_results','users'])if(!tables.has(t))throw new Error('Required database table missing: '+t);if(db.exec('PRAGMA user_version')[0].values[0][0]>1)throw new Error('Unsupported newer database schema');if(tables.has('reference_migrations')&&db.exec('SELECT MAX(version) FROM reference_migrations')[0].values[0][0]>3)throw new Error('Unsupported newer reference schema');if(db.exec('PRAGMA user_version')[0].values[0][0]===1)current=true;
if(current){for(const t of ['issued_reports','reference_interval_sets','parameter_critical_rules','reference_migrations','audit_log','test_rates','parameter_ranges','test_profiles','profile_parameters','formulas','patient_sequence','report_print_log','referrer_commission','order_commission_log','referrer_commission_pct','lab_print_profile'])if(!tables.has(t))throw new Error('Backup schema is unsupported; offline migration required');if(db.exec('PRAGMA user_version')[0].values[0][0]!==1)throw new Error('Backup schema is unsupported; offline migration required');}
if(db.exec('PRAGMA foreign_key_check').length)throw new Error('Database relationships are invalid');
for(const [table,col,parent]of [['orders','patient_id','patients'],['order_tests','order_id','orders'],['order_tests','parameter_id','parameters'],['order_results','order_id','orders'],['order_results','parameter_id','parameters'],['issued_reports','order_id','orders'],['reference_interval_sets','parameter_id','parameters'],['parameter_critical_rules','parameter_id','parameters']])if(tables.has(table)&&db.exec(`SELECT 1 FROM ${table} x LEFT JOIN ${parent} p ON p.id=x.${col} WHERE p.id IS NULL LIMIT 1`).length)throw new Error('Database relationships are invalid');
if(db.exec("SELECT 1 FROM sqlite_master WHERE type IN ('trigger','view') LIMIT 1").length)throw new Error('Unsupported executable schema objects');
if(current){
const schema=require('./databaseSchema.json');
for(const name of ['one_approved_reference','idx_orders_access_code'])if(!db.exec("SELECT 1 FROM sqlite_master WHERE type='index' AND name='"+name+"'").length)throw new Error('Required schema index missing: '+name);
for(const [name,required]of Object.entries(schema)){if(!tables.has(name))throw new Error('Required database table missing: '+name);const actual=new Set((db.exec(`PRAGMA table_info("${name}")`)[0]?.values||[]).map(row=>row[1]));for(const column of required)if(!actual.has(column))throw new Error('Required database column missing: '+name+'.'+column);}
for(const name of tables)if(!name.startsWith('sqlite_')&&!Object.hasOwn(schema,name))throw new Error('Unsupported database table: '+name);
if(db.exec('SELECT COUNT(*) FROM reference_migrations WHERE version IN (1,2,3)')[0].values[0][0]!==3)throw new Error('Incomplete database migrations');
for(const row of db.exec('SELECT username,password_hash,role FROM users')[0]?.values||[]){if(!row[0]||!['admin','staff'].includes(row[2])||!(/^[a-f0-9]{128}$/.test(row[1])||/^scrypt\$[a-f0-9]{32}\$[a-f0-9]{128}$/.test(row[1])))throw new Error('Invalid authentication records');}
if(db.exec("SELECT 1 FROM sqlite_master WHERE type IN ('trigger','view') LIMIT 1").length)throw new Error('Unsupported executable schema objects');
if(db.exec('SELECT 1 FROM order_results r LEFT JOIN order_tests t ON t.order_id=r.order_id AND t.parameter_id=r.parameter_id WHERE t.order_id IS NULL LIMIT 1').length)throw new Error('Results do not match ordered tests');
if(db.exec("SELECT 1 FROM orders o LEFT JOIN issued_reports r ON r.order_id=o.id WHERE o.report_status='issued' AND r.order_id IS NULL LIMIT 1").length)throw new Error('Issued report snapshot missing');
for(const row of db.exec('SELECT order_id,payload FROM issued_reports')[0]?.values||[]){let report;try{report=JSON.parse(row[1]);}catch{throw new Error('Invalid issued report snapshot');}if(!report||report.id!==row[0]||!report.patient_name||!Array.isArray(report.results)||!report.issued)throw new Error('Invalid issued report snapshot');}
for(const row of db.exec('SELECT rules FROM reference_interval_sets')[0]?.values||[])try{if(!Array.isArray(JSON.parse(row[0])))throw new Error();}catch{throw new Error('Invalid interval snapshot');}
}
const count=t=>db.exec(`SELECT COUNT(*) FROM ${t}`)[0].values[0][0];if((requireAdmin||count('users')>0)&&current&&!db.exec("SELECT 1 FROM users WHERE role='admin' LIMIT 1").length)throw new Error('Backup must contain an administrator');if(!count('users')&&count('patients'))throw new Error('Existing lab data without accounts requires administrator recovery');return {patients:count('patients'),orders:count('orders'),users:count('users'),issuedReports:tables.has('issued_reports')?count('issued_reports'):0};}finally{db.close();}}
module.exports={encrypt,decrypt,replace,inspect,passphrase};
