const crypto=require('crypto');
const {parseNumericResult}=require('./resultValidation.cjs');
const {classify}=require('./referenceIntervals.cjs').rules;
const audit=require('./applicationOperations.cjs').audit;
function id(n){if(!Number.isSafeInteger(n)||n<1)throw new Error('Invalid report identity');return n;}
function object(p,keys){if(!p||typeof p!=='object'||Array.isArray(p)||Object.keys(p).some(k=>!keys.includes(k)))throw new Error('Invalid amendment request');return p;}
function latest(db,order){return db.get('SELECT MAX(version) AS version FROM report_versions WHERE order_id=?',[order])?.version || 1;}
function version(db,order,n){const row=db.get('SELECT * FROM report_versions WHERE order_id=? AND version=?',[order,n]);if(!row)throw new Error('Issued report version not found');return {...JSON.parse(row.payload),report_version:n,parent_version:row.parent_version,amendment_reason:row.reason,amendment_changed_fields:JSON.parse(row.changed_fields)};}
function draft(db,draftId){if(typeof draftId!=='string')throw new Error('Invalid draft identity');const r=db.get('SELECT * FROM report_amendment_drafts WHERE id=?',[draftId]);if(!r)throw new Error('Amendment draft not found');return {...r,report:JSON.parse(r.payload)};}
function current(db,p){const r=draft(db,p.draftId);if(r.state!=='draft'||r.revision!==p.revision||latest(db,r.order_id)!==r.base_version)throw new Error('Amendment changed or is stale; reload before continuing');return r;}
function reason(s){if(typeof s!=='string'||s.trim().length<3||s.trim().length>1000)throw new Error('Provide an amendment reason (3–1000 characters)');return s.trim();}
module.exports={
 listReportVersions(orderId){id(orderId);return this.all('SELECT version,parent_version,issued_by,issued_at,reason,changed_fields FROM report_versions WHERE order_id=? ORDER BY version DESC',[orderId]).map(r=>({...r,changed_fields:JSON.parse(r.changed_fields)}));},
 getReportVersion(orderId,n){return version(this,id(orderId),id(n));},
 getReportAmendment(actor,orderId){this._referenceActor(actor,true);const r=this.get("SELECT id FROM report_amendment_drafts WHERE order_id=? AND state='draft'",[id(orderId)]);return r?draft(this,r.id):null;},
 createReportAmendment(actor,input){const user=this._referenceActor(actor,true),p=object(input,['orderId','baseVersion','reason','requestId']);id(p.orderId);id(p.baseVersion);const why=reason(p.reason);if(typeof p.requestId!=='string'||! /^[a-f0-9-]{36}$/i.test(p.requestId))throw new Error('A unique request identity is required');const request=JSON.stringify([p.orderId,p.baseVersion,why]);return this._referenceAtomic(()=>{const old=this.get('SELECT * FROM report_amendment_requests WHERE request_id=?',[p.requestId]);if(old){if(old.actor_id!==user.id||old.request!==request)throw new Error('Request identity reused for a different amendment');return draft(this,old.draft_id);}if(latest(this,p.orderId)!==p.baseVersion)throw new Error('Report changed; reload latest version');if(this.get("SELECT id FROM report_amendment_drafts WHERE order_id=? AND state='draft'",[p.orderId]))throw new Error('An amendment draft already exists; resume it');const report={...version(this,p.orderId,p.baseVersion),issued:false},now=new Date().toISOString(),draftId=crypto.randomUUID();this.db.run('INSERT INTO report_amendment_drafts(id,order_id,base_version,revision,payload,reason,created_by,state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,\'draft\',?,?)',[draftId,p.orderId,p.baseVersion,1,JSON.stringify(report),why,user.id,now,now]);this.db.run('INSERT INTO report_amendment_requests VALUES(?,?,?,?)',[p.requestId,user.id,request,draftId]);audit(this,user,'report-amendment-created',p.orderId,{draftId,baseVersion:p.baseVersion,reason:why});return draft(this,draftId);});},
 saveReportAmendment(actor,input){const user=this._referenceActor(actor,true),p=object(input,['draftId','revision','changes']);id(p.revision);if(!Array.isArray(p.changes)||!p.changes.length||p.changes.length>1000)throw new Error('Provide result corrections');return this._referenceAtomic(()=>{const d=current(this,p),report=d.report,seen=new Set();require('./reportVersionIntegrity.cjs').validate(version(this,d.order_id,d.base_version),report,{draft:true});for(const c of p.changes){object(c,['parameterId','value']);id(c.parameterId);if(seen.has(c.parameterId))throw new Error('Duplicate result correction');seen.add(c.parameterId);const row=report.results.find(r=>r.parameter_id===c.parameterId);if(!row)throw new Error('Only existing ordered results may be corrected');const provenance=row.clinical_provenance;const type=provenance?.parameter?.type || this.get('SELECT type FROM parameters WHERE id=?',[c.parameterId])?.type;if(type==='derived')throw new Error('Derived result correction requires validated formula review; automatic recomputation is unavailable');if(type==='text'){if(typeof c.value!=='string'||!c.value.trim()||c.value.length>10000)throw new Error('A non-empty text result is required');row.result_text=c.value.trim();row.result_value=null;row.raw_result_value=null;row.flag='';}else if(type==='numeric'){const n=parseNumericResult(c.value);if(n===null)throw new Error('A corrected numeric result cannot be blank');row.result_value=n;row.raw_result_value=n;row.result_text=null;row.flag=provenance?classify(n,row.reference_interval,provenance.critical_rule):'';}else throw new Error('Saved result type is unavailable; correction cannot be validated safely');row.review_message=provenance?row.review_message:'Historical clinical provenance is incomplete; corrected result requires manual clinical review; automatic flags withheld';row.amendment_provenance={source_version:d.base_version,reference_interval:row.reference_interval || null,unit:row.unit || '',clinical_provenance:provenance || null,manual_review:!provenance};}
 // A changed measured result can invalidate a saved derived result. Never silently retain it.
 const derived=report.results.filter(r=>r.clinical_provenance?.parameter?.type==='derived'||this.get('SELECT type FROM parameters WHERE id=?',[r.parameter_id])?.type==='derived');const done=new Set(),visiting=new Set();const recalc=row=>{if(done.has(row.parameter_id))return;const cp=row.clinical_provenance,f=cp?.formula;if(!f||!Array.isArray(f.dependencies)||typeof f.expression!=='string'||!Number.isInteger(f.precision)||f.precision<0||f.precision>12)throw new Error('Derived provenance is incomplete; correction requires validated formula review');if(visiting.has(row.parameter_id))throw new Error('Saved derived formula has cyclic dependencies');visiting.add(row.parameter_id);if(f.output_unit!==undefined && f.output_unit!==row.unit)throw new Error('Saved formula output units are incompatible');let expr=f.expression,affected=false;const vals={};for(const code of f.dependencies){const dep=report.results.find(r=>(r.clinical_provenance?.parameter?.code || r.code)===code);if(!dep)throw new Error('Saved derived dependency is missing');if(dep.clinical_provenance?.parameter?.type==='derived')recalc(dep);if(seen.has(dep.parameter_id))affected=true;const n=parseNumericResult(dep.result_value);if(n===null)throw new Error('Saved derived dependency is missing');vals[code]=n;const expected=f.input_units?.[code];if(expected!==undefined&&expected!==dep.unit)throw new Error('Saved formula units are incompatible');if(!/^[A-Za-z][A-Za-z0-9_]*$/.test(code))throw new Error('Unsupported dependency code');const escaped=code;expr=expr.replace(new RegExp('\\b'+escaped+'\\b','g'),String(n));}if(affected){if((cp.parameter.code==='LDL'&&vals.TG>400)||(cp.parameter.code==='AGRATIO'&&vals.GLOB===0))throw new Error('Corrected derived result cannot be calculated reliably');if(expr.length>10000||!/^[0-9eE\s.+*/%()\-]+$/.test(expr))throw new Error('Unsupported saved formula');const raw=Function('"use strict";return ('+expr+')')();if(!Number.isFinite(raw))throw new Error('Corrected derived result is non-finite');row.result_value=Number(raw.toFixed(f.precision));row.raw_result_value=raw;row.result_text=null;row.flag=classify(raw,row.reference_interval,cp.critical_rule);row.clinical_provenance={...cp,formula:{...f,raw_value:raw,provenance:'recomputed-from-issued-snapshot'}};row.amendment_provenance={source_version:d.base_version,reference_interval:row.reference_interval || null,unit:row.unit || '',clinical_provenance:row.clinical_provenance,manual_review:false};seen.add(row.parameter_id);}visiting.delete(row.parameter_id);done.add(row.parameter_id);};derived.forEach(recalc);
 this.db.run('UPDATE report_amendment_drafts SET payload=?,revision=revision+1,updated_at=? WHERE id=?',[JSON.stringify(report),new Date().toISOString(),d.id]);audit(this,user,'report-amendment-saved',d.order_id,{draftId:d.id,parameterIds:[...seen]});return draft(this,d.id);});},
 finalizeReportAmendment(actor,input){const user=this._referenceActor(actor,true),p=object(input,['draftId','revision']);id(p.revision);return this._referenceAtomic(()=>{let d=draft(this,p.draftId);if(d.state==='finalized'){if(p.revision!==d.revision)throw new Error('Finalization revision mismatch');return version(this,d.order_id,d.final_version);}d=current(this,p);const base=version(this,d.order_id,d.base_version);require('./reportVersionIntegrity.cjs').validate(base,d.report,{draft:true});const changed=d.report.results.filter((r,i)=>JSON.stringify(r)!==JSON.stringify(base.results[i])).map(r=>r.parameter_id);if(!changed.length)throw new Error('No result corrections have been saved');const n=d.base_version+1,now=new Date().toISOString(),report={...d.report,issued:true,report_version:n,parent_version:d.base_version,amendment_reason:d.reason,amendment_changed_fields:changed,issued_at:now,report_date:now,issued_by:user.username,report_printed_by:user.displayName || user.username};this.db.run('INSERT INTO report_versions VALUES(?,?,?,?,?,?,?,?)',[d.order_id,n,d.base_version,JSON.stringify(report),user.username,now,d.reason,JSON.stringify(changed)]);this.db.run("UPDATE report_amendment_drafts SET state='finalized',final_version=?,updated_at=? WHERE id=?",[n,now,d.id]);audit(this,user,'report-amendment-finalized',d.order_id,{draftId:d.id,version:n,parentVersion:d.base_version,reason:d.reason,changedFields:changed});return report;});},
 cancelReportAmendment(actor,input){const user=this._referenceActor(actor,true),p=object(input,['draftId','revision']);id(p.revision);return this._referenceAtomic(()=>{const d=current(this,p);this.db.run("UPDATE report_amendment_drafts SET state='cancelled',updated_at=? WHERE id=?",[new Date().toISOString(),d.id]);audit(this,user,'report-amendment-cancelled',d.order_id,{draftId:d.id});return {ok:true};});}
};
