import {useState} from 'react';
export default function RecoverySettings(){
 const [pass,setPass]=useState(''),[candidate,setCandidate]=useState(null),[confirmation,setConfirmation]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [current,setCurrent]=useState(''),[next,setNext]=useState('');
 async function run(fn){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 return <details className="advanced-settings"><summary>Credentials & validated recovery<small>Change your password or restore an authenticated encrypted backup.</small></summary><div className="settings-section recovery-settings" data-ui="section">
 <h3>Change your password</h3><label htmlFor="credential-current">Current password</label><input data-ui="input" id="credential-current" type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/><label htmlFor="credential-next">New password (at least 12 characters)</label><input data-ui="input" id="credential-next" type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)}/><button data-ui="btn" disabled={busy} onClick={()=>run(async()=>{await window.db.changePassword(current,next);setCurrent('');setNext('');window.location.reload();})}>Change password and sign out</button>
 <h3>Restore encrypted backup</h3><p>Administrator authorization is required. All current lab data will be replaced. A verified local recovery copy is created first. Successful restoration signs everyone out.</p><p>A lost backup passphrase cannot be recovered. Legacy raw/CBC backups require offline review and are not accepted here.</p>
 <label htmlFor="restore-passphrase">Backup passphrase</label><input data-ui="input" id="restore-passphrase" type="password" autoComplete="off" value={pass} onChange={e=>setPass(e.target.value)} disabled={busy||!!candidate}/><button data-ui="btn" disabled={busy||!!candidate} onClick={()=>run(async()=>{const value=await window.db.prepareRestore(pass);setPass('');if(!value.canceled)setCandidate(value);})}>Select and validate backup…</button>
 {candidate&&<div role="region" aria-label="Restore confirmation"><h4>Validated restore summary</h4><p>{candidate.summary.patients} patients · {candidate.summary.orders} orders · {candidate.summary.issuedReports} issued reports · {candidate.summary.users} users</p><p>This replaces the complete database, including accounts and audit history.</p><label htmlFor="restore-confirm">Type RESTORE to confirm replacement</label><input data-ui="input" id="restore-confirm" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/><button data-ui="btn" disabled={busy||confirmation!=='RESTORE'} onClick={()=>run(async()=>{await window.db.confirmRestore(candidate.token,confirmation);window.location.reload();})}>Restore database and sign out</button><button data-ui="btn btnSecondary" disabled={busy} onClick={()=>run(async()=>{await window.db.cancelRestore(candidate.token);setCandidate(null);setConfirmation('');})}>Cancel restore</button></div>}
 {message&&<p role="alert" data-ui="message">{message}</p>}
 </div></details>;
}
