'use strict';
const $=id=>document.getElementById(id);
const state={view:'customers',customers:[],licenses:[],activations:[],events:[],nextCursor:null,customerId:'',query:'',submit:null,busy:false};
const names={customers:['Customers','Manage lab access and invitation status.','Add customer'],licenses:['Licences & trials','Set explicit expiry, device seats and offline allowance.','Create licence'],history:['Activity & audit','Authenticated changes to licensing metadata.','']};
function node(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);if(className)e.className=className;return e;}
function feedback(message,error=false){$('feedback').textContent=message;$('feedback').className=error?'error':'';$('feedback').hidden=!message;}
async function api(action,data={}){const res=await fetch('/v1/owner/'+action,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Patholy-Owner-Action':'1'},body:JSON.stringify(data),redirect:'error'});let result;try{result=await res.json();}catch{throw new Error('Your owner session may have ended. Reload and sign in through Cloudflare Access.');}if(!res.ok)throw new Error(res.status===403?'Permission denied. Sign in with the authorized owner identity.':result.error||'The request could not be completed. Retry without changing your selection.');return result;}
const date=seconds=>new Date(seconds*1000).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
function status(value){return node('span',value,'status'+(['active','enabled'].includes(value)?'':' review'));}
function action(label,callback){const b=node('button',label);b.type='button';b.addEventListener('click',callback);return b;}
function cell(content,sub){const td=node('td');td.append(typeof content==='string'?node('strong',content):content);if(sub)td.append(node('div',sub,'sub'));return td;}
function table(headers,rows){const table=node('table');const thead=node('thead');const tr=node('tr');headers.forEach(h=>tr.append(node('th',h)));thead.append(tr);table.append(thead);const body=node('tbody');rows.forEach(r=>body.append(r));table.append(body);return table;}
function empty(title,description){const e=node('div',undefined,'empty');e.append(node('strong',title),node('span',description));return e;}
function render(){const content=$('content');content.replaceChildren();const query=state.query.toLowerCase();let count=0;
 if(state.view==='customers'){const customers=state.customers.filter(c=>[c.display_name,c.email,c.id].join(' ').toLowerCase().includes(query));count=customers.length;content.append(customers.length?table(['Customer','Access','Identity','Actions'],customers.map(c=>{const tr=node('tr'),a=node('div',undefined,'row-actions');a.append(action('Licences',()=>{state.customerId=c.id;changeView('licenses');}),action(c.status==='disabled'?'Reactivate':'Disable',()=>confirmChange('Customer '+(c.status==='disabled'?'reactivation':'disable'),c.display_name,'customers/'+(c.status==='disabled'?'enable':'disable'),{customerId:c.id})),action('Invite',()=>invite(c)));tr.append(cell(c.display_name,c.email),cell(status(c.status)),cell(c.identity_subject?'Linked identity':'Invitation required',c.id),cell(a));return tr;})):empty('No customers found','Add a customer or adjust the search.'));}
 if(state.view==='licenses'){const chooser=node('label',undefined,'field');chooser.textContent='Customer';const select=node('select');select.id='customer-select';select.append(new Option('Select a customer',''));state.customers.forEach(c=>select.append(new Option(c.display_name,c.id)));select.value=state.customerId;select.addEventListener('change',()=>{state.customerId=select.value;load();});chooser.append(select);chooser.classList.add('customer-chooser');content.append(chooser);const licenses=state.licenses.filter(l=>[l.id,l.kind,l.status].join(' ').toLowerCase().includes(query));count=licenses.length;if(!state.customerId){content.append(empty('Choose a customer','Licences and trials belong to a specific lab customer.'));return;}
 content.append(licenses.length?table(['Licence','Policy','Status','Actions'],licenses.map(l=>{const tr=node('tr'),a=node('div',undefined,'row-actions');a.append(action('Extend / policy',()=>policy(l)),action(l.suspended||l.status==='revoked'?'Reactivate':'Suspend',()=>confirmChange(l.suspended||l.status==='revoked'?'Reactivate licence':'Suspend licence',l.id+(l.expires_at*1000<Date.now()?' (expired: extend the policy before reactivation)':''),'licenses/'+(l.suspended||l.status==='revoked'?'reactivate':'suspend'),{licenseId:l.id})),action('Revoke',()=>confirmChange('Revoke licence',l.id,'licenses/revoke',{licenseId:l.id})),action('Devices',()=>devices(l)));tr.append(cell(l.kind==='trial'?'Trial':'Licence',l.id),cell(`${l.active_seats||0} / ${l.seats} device seats`,`${date(l.expires_at)} · ${l.offline_seconds} seconds offline`),cell(status(l.suspended?'suspended':l.status)),cell(a));return tr;})):empty('No licences yet','Create a licence or trial with an explicitly chosen policy.'));const history=state.activations;if(history.length){content.append(node('h2','Device history','history-title'),table(['Licence / installation','Activation status','Created'],history.map(a=>{const tr=node('tr');tr.append(cell(a.device_id,a.license_id),cell(status(a.status)),cell(date(a.created_at)));return tr;})));}}
 if(state.view==='history'){const events=state.events.filter(e=>[e.actor,e.action,e.customer_id,e.license_id].join(' ').toLowerCase().includes(query));count=events.length;content.append(events.length?table(['When','Action','Authenticated actor','Record'],events.map(e=>{const tr=node('tr');tr.append(cell(date(e.created_at)),cell(e.action),cell(e.actor),cell(e.license_id||e.customer_id||'—',typeof e.details==='string'?e.details:JSON.stringify(e.details||{})));return tr;})):empty('No activity found','Owner changes are recorded by the licensing service.'));content.append(node('p','History loads in pages of up to 1,000 events. No older events are removed.','audit-pagination'));if(state.nextCursor){const more=action('Load older activity',loadMoreAudit);more.className='secondary audit-more';content.append(more);}}
 $('count').textContent=count+' '+(state.view==='history'?'events':'records');}
async function load(){if(state.busy){state.pendingLoad=true;return;}state.busy=true;$('content').setAttribute('aria-busy','true');$('refresh').disabled=true;try{const result=await api('customers/list');state.customers=result.customers||[];$('identity').textContent='Owner · Cloudflare Access';if(state.view==='licenses'){if(state.customerId){const result=await api('licenses/list',{customerId:state.customerId});state.licenses=result.licenses||[];state.activations=result.activations||[];}else{state.licenses=[];state.activations=[];}}if(state.view==='history'){const audit=await api('audit/list');state.events=audit.events||[];state.nextCursor=audit.nextCursor||null;}render();}catch(e){feedback(e.message,true);$('content').replaceChildren(empty('Owner access unavailable','Reload and sign in with your authorized Cloudflare Access identity.'));$('count').textContent='Unavailable';}finally{state.busy=false;$('content').setAttribute('aria-busy','false');$('refresh').disabled=false;if(state.pendingLoad){state.pendingLoad=false;load();}}}
async function loadMoreAudit(){if(state.busy||!state.nextCursor)return;state.busy=true;try{const result=await api('audit/list',{cursor:state.nextCursor});if(state.view==='history'){state.events.push(...(result.events||[]));state.nextCursor=result.nextCursor||null;render();}}catch(e){feedback(e.message,true);}finally{state.busy=false;}}
function changeView(view){state.view=view;state.query='';$('search').value='';const [title,description,create]=names[view];$('title').textContent=title;$('description').textContent=description;$('create').textContent=create;$('create').hidden=!create;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===view));feedback('');load();}
function openForm(title,fields,submit,note,submitLabel='Save'){$('dialog-title').textContent=title;$('fields').replaceChildren();$('form-error').hidden=true;$('submit').textContent=submitLabel;for(const f of fields){const label=node('label',undefined,'field');label.append(node('span',f.label));const input=f.options?node('select'):node('input');input.name=f.name;input.setAttribute('aria-label',f.label);input.required=f.required!==false;if(!f.options)input.type=f.type||'text';if(f.options)f.options.forEach(([value,text])=>input.append(new Option(text,value)));if(f.min!==undefined)input.min=f.min;if(f.max!==undefined)input.max=f.max;if(f.step)input.step=f.step;if(f.value!==undefined)input.value=f.value;label.append(input);if(f.help){const help=node('small',f.help);help.id='help-'+f.name;input.setAttribute('aria-describedby',help.id);label.append(help);}$('fields').append(label);}if(note)$('fields').append(node('p',note,'dialog-note'));state.submit=submit;$('editor').showModal();}
function closeForm(){$('editor').close();state.submit=null;}
function confirmChange(title,record,route,data){openForm(title,[],async()=>{await api(route,data);return {};},'Confirm this change for '+record+'. Existing clinical records are never deleted. Offline grants can continue until their allowance ends.','Confirm');}
function addCustomer(){openForm('Add customer',[{name:'displayName',label:'Lab / customer name'},{name:'email',label:'Customer identity email',type:'email'}],data=>api('customers/create',data),'Customer access uses an external identity provider. No customer password is created or stored here.');}
function invite(c){openForm('Invite '+c.display_name,[{name:'expiresAt',label:'Invitation expires',type:'datetime-local',help:'The invitation must be redeemed once by this customer’s verified identity.'}],data=>api('customers/invite',{customerId:c.id,expiresAt:Math.floor(new Date(data.expiresAt).getTime()/1000)}),'Send the one-time token securely to '+c.email+'. The licensing service does not send email automatically.','Create invitation');}
function policy(existing){if(!existing&&!state.customerId){feedback('Choose a customer before creating a licence.',true);return;}const fields=[];if(!existing)fields.push({name:'kind',label:'Type',options:[['','Choose licence or trial'],['licence','Licence'],['trial','Trial']]});fields.push({name:'expiresAt',label:'Expires',type:'datetime-local',value:existing?localDate(existing.expires_at):undefined},{name:'seats',label:'Device seats',type:'number',min:1,max:10000,step:1,value:existing?.seats},{name:'offlineSeconds',label:'Offline allowance (seconds)',type:'number',min:1,max:31536000,step:1,value:existing?.offline_seconds,help:'Choose explicitly. This also bounds how long offline revocation may take.'});openForm(existing?'Extend licence / change policy':'Create licence or trial',fields,data=>api('licenses/'+(existing?'renew':'create'),{...(existing?{licenseId:existing.id}:{customerId:state.customerId,kind:data.kind}),expiresAt:Math.floor(new Date(data.expiresAt).getTime()/1000),seats:Number(data.seats),offlineSeconds:Number(data.offlineSeconds)}),'No annual, seat-count or offline-period business defaults are assumed.');}
function localDate(seconds){const d=new Date(seconds*1000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function devices(l){const acts=state.activations.filter(a=>a.license_id===l.id&&a.status==='active');if(!acts.length){feedback('This licence has no active devices.');return;}openForm('Manage device seat',[{name:'activationId',label:'Active installation',options:[['','Choose an installation'],...acts.map(a=>[a.id,a.device_id])]},{name:'action',label:'Action',options:[['','Choose an action'],['reset','Reset / revoke this seat'],['transfer','Transfer to a new installation']]},{name:'deviceId',label:'New installation ID (for transfer)',required:false,help:'Copy the 64-character installation ID from the new app’s licence settings.'}],data=>{if(data.action==='transfer'&&!/^[a-f0-9]{64}$/.test(data.deviceId))throw new Error('Enter the new installation’s 64-character ID.');return api('licenses/'+data.action,{licenseId:l.id,activationId:data.activationId,...(data.action==='transfer'?{deviceId:data.deviceId}:{})});},'Reset or transfer revokes the old seat. Existing offline grants remain usable until their offline allowance ends.','Confirm device change');}
function showSecret(result){const value=result.key||(result.inviteToken?new URL('/invite',location.origin).href+'#token='+encodeURIComponent(result.inviteToken):'');if(!value)return;$('secret-title').textContent=result.key?'Licence key · shown once':'Invitation token · shown once';$('secret').value=value;$('copy-status').textContent='';$('secret-dialog').showModal();}
$('form').addEventListener('submit',async e=>{e.preventDefault();if(!state.submit)return;$('submit').disabled=true;$('form-error').hidden=true;try{const result=await state.submit(Object.fromEntries(new FormData($('form'))));closeForm();feedback('Change saved.');showSecret(result);await load();}catch(error){$('form-error').textContent=error.message;$('form-error').hidden=false;}finally{$('submit').disabled=false;}});
$('close').addEventListener('click',closeForm);$('cancel').addEventListener('click',closeForm);$('editor').addEventListener('cancel',()=>{state.submit=null;});$('create').addEventListener('click',()=>state.view==='customers'?addCustomer():policy());$('refresh').addEventListener('click',()=>{feedback('');load();});$('search').addEventListener('input',e=>{state.query=e.target.value;render();});document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>changeView(b.dataset.view)));
function clearSecret(){$('secret').value='';$('copy-status').textContent='';}$('secret-dialog').addEventListener('close',clearSecret);$('secret-dialog').addEventListener('cancel',clearSecret);$('done-secret').addEventListener('click',()=>{$('secret-dialog').close();clearSecret();});$('copy-secret').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('secret').value);$('copy-status').textContent='Copied. Clear your clipboard after secure delivery.';}catch{$('copy-status').textContent='Select and copy the value manually.';}});load();
