'use strict';
const $=id=>document.getElementById(id);
const state={view:'customers',customers:[],licenses:[],activations:[],events:[],nextCursor:null,customerId:'',query:'',submit:null,busy:false,generation:0,customerQuery:'',customerCursor:null,licenseCursor:null,deviceCursor:null,revocationCursor:null,revocations:[],pageBusy:new Set(),pageTokens:{},customerRequests:0,modalGeneration:0,selectedCustomer:null};
const names={customers:['Customers','Manage lab access and invitation status.','Add customer'],licenses:['Licences & trials','Set explicit expiry, device seats and offline allowance.','Create licence'],history:['Activity & audit','Authenticated changes to licensing metadata.','']};
function node(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);if(className)e.className=className;return e;}
function feedback(message,error=false){$('feedback').textContent=message;$('feedback').className=error?'error':'';$('feedback').hidden=!message;}
async function api(action,data={}){const res=await fetch('/v1/owner/'+action,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Patholy-Owner-Action':'1'},body:JSON.stringify(data),redirect:'error'});let result;try{result=await res.json();}catch{throw new Error('Your owner session may have ended. Reload and sign in again with your owner password and second factor.');}if(!res.ok)throw new Error(res.status===403?'Permission denied. Sign in with the authorized owner identity.':result.error||'The request could not be completed. Retry without changing your selection.');return result;}
const date=seconds=>new Date(seconds*1000).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
function status(value){return node('span',value,'status'+(['active','enabled'].includes(value)?'':' review'));}
function action(label,callback){const b=node('button',label);b.type='button';b.addEventListener('click',callback);return b;}
function cell(content,sub){const td=node('td');td.append(typeof content==='string'?node('strong',content):content);if(sub)td.append(node('div',sub,'sub'));return td;}
function table(headers,rows){const table=node('table');const thead=node('thead');const tr=node('tr');headers.forEach(h=>tr.append(node('th',h)));thead.append(tr);table.append(thead);const body=node('tbody');rows.forEach(r=>body.append(r));table.append(body);return table;}
function empty(title,description){const e=node('div',undefined,'empty');e.append(node('strong',title),node('span',description));return e;}
function render(){const content=$('content');content.replaceChildren();const query=state.view==='customers'?'':state.query.toLowerCase();let count=0;
 if(state.view==='customers'){const customers=state.customers.filter(c=>[c.display_name,c.email,c.id].join(' ').toLowerCase().includes(query));count=customers.length;content.append(customers.length?table(['Customer','Access','Identity','Actions'],customers.map(c=>{const tr=node('tr'),a=node('div',undefined,'row-actions');a.append(action('Licences',()=>{state.customerId=c.id;state.selectedCustomer=c;changeView('licenses');}),action(c.status==='disabled'?'Reactivate':'Disable',()=>confirmChange('Customer '+(c.status==='disabled'?'reactivation':'disable'),c.display_name,'customers/'+(c.status==='disabled'?'enable':'disable'),{customerId:c.id})),...(document.querySelector('meta[name=patholy-customer-portal]')?.content==='false'?[]:[action('Invite',()=>invite(c))]));tr.append(cell(c.display_name,c.email),cell(status(c.status)),cell(document.querySelector('meta[name=patholy-customer-portal]')?.content==='false'?'Manual key delivery':c.identity_subject?'Linked identity':'Optional portal invitation',c.id),cell(a));return tr;})):empty('No customers found','Add a customer or adjust the search.'));pagination(content,'customers',state.customerCursor,'Load more customers');}
 if(state.view==='licenses'){const chooser=node('label',undefined,'field');chooser.textContent='Customer';const select=node('select');select.id='customer-select';select.append(new Option('Select a customer',''));const choices=[...state.customers];if(state.selectedCustomer&&!choices.some(c=>c.id===state.selectedCustomer.id))choices.push(state.selectedCustomer);choices.forEach(c=>select.append(new Option(c.display_name,c.id)));select.value=state.customerId;select.addEventListener('change',()=>{state.customerId=select.value;state.selectedCustomer=choices.find(c=>c.id===select.value)||null;load();});chooser.append(select);chooser.classList.add('customer-chooser');const lookup=node('input');lookup.type='search';lookup.value=state.customerQuery;lookup.placeholder='Search all customers by name or email';lookup.setAttribute('aria-label','Find customer');let lookupTimer;lookup.addEventListener('input',()=>{clearTimeout(lookupTimer);const value=lookup.value;lookupTimer=setTimeout(()=>searchCustomers(value),300);});chooser.append(lookup);content.append(chooser);pagination(content,'customers',state.customerCursor,'Load more customers');const licenses=state.licenses.filter(l=>[l.id,l.kind,l.status].join(' ').toLowerCase().includes(query));count=licenses.length;if(!state.customerId){content.append(empty('Choose a customer','Licences and trials belong to a specific lab customer.'));return;}
 content.append(licenses.length?table(['Licence','Policy','Status','Actions'],licenses.map(l=>{const tr=node('tr'),a=node('div',undefined,'row-actions');a.append(action('Extend / policy',()=>policy(l)),action(l.suspended||l.status==='revoked'?'Reactivate':'Suspend',()=>confirmChange(l.suspended||l.status==='revoked'?'Reactivate licence':'Suspend licence',l.id+(l.expires_at>0&&l.expires_at*1000<Date.now()?' (expired: extend the policy before reactivation)':''),'licenses/'+(l.suspended||l.status==='revoked'?'reactivate':'suspend'),{licenseId:l.id})),action('Revoke',()=>confirmChange('Revoke licence',l.id,'licenses/revoke',{licenseId:l.id})),action('Devices',()=>devices(l)));tr.append(cell(l.kind==='trial'?'Trial':'Licence',l.id),cell(`${l.active_seats||0} / ${l.seats} device seats`,`${l.kind==='trial'&&!l.trial_started_at?'Awaiting first activation':date(l.expires_at)} · ${l.offline_seconds} seconds offline`),cell(status(l.suspended?'suspended':l.status)),cell(a));return tr;})):empty('No licences yet','Create a licence or trial with an explicitly chosen policy.'));pagination(content,'licenses',state.licenseCursor,'Load more licences');const history=state.activations;if(history.length){content.append(node('h2','Device history','history-title'),table(['Licence / installation','Activation status','Created'],history.map(a=>{const tr=node('tr');tr.append(cell(a.device_id,a.license_id),cell(status(a.status)),cell(date(a.created_at)));return tr;})));}pagination(content,'devices',state.deviceCursor,'Load more device history');if(state.revocations.length){content.append(node('h2','Revocation history','history-title'),table(['When','Licence / activation','Actor'],state.revocations.map(r=>{const tr=node('tr');tr.append(cell(date(r.created_at)),cell(r.license_id,r.activation_id||'Entire licence'),cell(r.actor));return tr;})));}pagination(content,'revocations',state.revocationCursor,'Load more revocations');}
 if(state.view==='history'){const events=state.events.filter(e=>[e.actor,e.action,e.customer_id,e.license_id].join(' ').toLowerCase().includes(query));count=events.length;content.append(events.length?table(['When','Action','Authenticated actor','Record'],events.map(e=>{const tr=node('tr');tr.append(cell(date(e.created_at)),cell(e.action),cell(e.actor),cell(e.license_id||e.customer_id||'â€”',typeof e.details==='string'?e.details:JSON.stringify(e.details||{})));return tr;})):empty('No activity found','Owner changes are recorded by the licensing service.'));content.append(node('p','History loads in pages of up to 1,000 events. No older events are removed.','audit-pagination'));if(state.nextCursor){const more=action('Load older activity',loadMoreAudit);more.className='secondary audit-more';content.append(more);}}
 $('count').textContent=count+' '+(state.view==='history'?'events':'records');}
function context(){return {generation:state.generation,view:state.view,customerId:state.customerId};}
function current(c){return c.generation===state.generation&&c.view===state.view&&c.customerId===state.customerId;}
function merge(existing,rows){const ids=new Set(existing.map(r=>r.id));return [...existing,...rows.filter(r=>!ids.has(r.id))];}
function pagination(container,stream,cursor,label){const note=node('p',stream==='customers'?'Customer search covers all records. Load more to browse the next page.':'Search filters loaded records. Load more to include older records.','audit-pagination');container.append(note);if(cursor){const b=action(label,()=>loadPage(stream));b.className='secondary audit-more';b.disabled=state.pageBusy.has(stream);container.append(b);}}
function listFailure(e){state.generation++;state.customers=[];state.licenses=[];state.activations=[];state.revocations=[];state.events=[];state.customerCursor=state.licenseCursor=state.deviceCursor=state.revocationCursor=state.nextCursor=null;state.pageBusy.clear();state.pageTokens={};state.busy=false;$('content').setAttribute('aria-busy','false');$('refresh').disabled=false;feedback(e.message,true);$('content').replaceChildren(empty('Owner access unavailable','Reload and sign in with your owner password and second factor.'));$('count').textContent='Unavailable';}
async function searchCustomers(query){state.customerQuery=query;const request=++state.customerRequests,c=context();state.pageBusy.delete('customers');delete state.pageTokens.customers;try{const result=await api('customers/list',query?{query}:{});if(!current(c)||request!==state.customerRequests)return;state.customers=result.customers||[];state.customerCursor=result.nextCursor||null;render();}catch(e){if(current(c)&&request===state.customerRequests)listFailure(e);}}
async function load(){if(state.view==='customers')state.customerQuery=state.query;const c={...context(),generation:++state.generation};state.busy=true;state.pageBusy.clear();state.pageTokens={};if(c.view==='licenses'){state.licenses=[];state.activations=[];state.revocations=[];state.licenseCursor=state.deviceCursor=state.revocationCursor=null;render();}$('content').setAttribute('aria-busy','true');$('refresh').disabled=true;try{if(c.view==='customers'||!state.customers.length){const query=c.view==='customers'?state.query:state.customerQuery;const result=await api('customers/list',query?{query}:{});if(!current(c))return;state.customerQuery=query;state.customers=result.customers||[];state.customerCursor=result.nextCursor||null;}$('identity').textContent=document.querySelector('meta[name=patholy-owner-auth]')?.content==='workos'?'iamrobiul94@gmail.com · MFA verified':'Owner · Cloudflare Access';if(c.view==='licenses'){if(c.customerId){const result=await api('licenses/list',{customerId:c.customerId});if(!current(c))return;state.licenses=result.licenses||[];state.activations=result.activations||[];state.revocations=result.revocations||[];state.licenseCursor=result.nextCursor||result.nextCursors?.licenses||null;state.deviceCursor=result.nextCursors?.activations||null;state.revocationCursor=result.nextCursors?.revocations||null;}else{state.licenses=[];state.activations=[];state.revocations=[];state.licenseCursor=state.deviceCursor=state.revocationCursor=null;}}if(c.view==='history'){const result=await api('audit/list');if(!current(c))return;state.events=result.events||[];state.nextCursor=result.nextCursor||null;}if(current(c))render();}catch(e){if(current(c))listFailure(e);}finally{if(current(c)){state.busy=false;$('content').setAttribute('aria-busy','false');$('refresh').disabled=false;}}}
async function loadPage(stream){if(state.pageBusy.has(stream))return;const c=context(),customerRequest=state.customerRequests,customerQuery=state.customerQuery;const map={customers:['customers/list','customers','customerCursor'],licenses:['licenses/list','licenses','licenseCursor'],devices:['devices/list','activations','deviceCursor'],revocations:['revocations/list','revocations','revocationCursor'],audit:['audit/list','events','nextCursor']};const [route,rows,cursor]=map[stream];if(!state[cursor])return;const data={cursor:state[cursor],...(stream==='customers'?(state.customerQuery?{query:state.customerQuery}:{}):stream==='audit'?{}:{customerId:c.customerId})};const token=Symbol(stream);state.pageTokens[stream]=token;state.pageBusy.add(stream);const pageCurrent=()=>current(c)&&(stream!=='customers'||(customerRequest===state.customerRequests&&customerQuery===state.customerQuery));render();try{const result=await api(route,data);if(!pageCurrent())return;state[rows]=merge(state[rows],result[rows]||[]);state[cursor]=result.nextCursor||null;render();}catch(e){if(pageCurrent())listFailure(e);}finally{if(current(c)&&state.pageTokens[stream]===token){delete state.pageTokens[stream];state.pageBusy.delete(stream);const buttons=$('content').querySelectorAll('button');buttons.forEach(b=>{if(b.textContent.startsWith('Load '))b.disabled=false;});}}}
async function loadMoreAudit(){return loadPage('audit');}
function changeView(view){state.view=view;state.query='';$('search').value='';$('search').placeholder=view==='customers'?'Search all customers by name or email':'Search loaded records';const [title,description,create]=names[view];$('title').textContent=title;$('description').textContent=description;$('create').textContent=create;$('create').hidden=!create;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===view));feedback('');load();}
function openForm(title,fields,submit,note,submitLabel='Save'){$('dialog-title').textContent=title;$('fields').replaceChildren();$('form-error').hidden=true;$('submit').textContent=submitLabel;for(const f of fields){const label=node('label',undefined,'field');label.append(node('span',f.label));const input=f.options?node('select'):node('input');input.name=f.name;input.setAttribute('aria-label',f.label);input.required=f.required!==false;if(!f.options)input.type=f.type||'text';if(f.options)f.options.forEach(([value,text])=>input.append(new Option(text,value)));if(f.min!==undefined)input.min=f.min;if(f.max!==undefined)input.max=f.max;if(f.step)input.step=f.step;if(f.value!==undefined)input.value=f.value;label.append(input);if(f.help){const help=node('small',f.help);help.id='help-'+f.name;input.setAttribute('aria-describedby',help.id);label.append(help);}$('fields').append(label);}if(note)$('fields').append(node('p',note,'dialog-note'));state.submit=submit;$('editor').showModal();}
function closeForm(){state.modalGeneration++;$('editor').close();state.submit=null;}
function confirmChange(title,record,route,data){openForm(title,[],async()=>{await api(route,data);return {};},'Confirm this change for '+record+'. Existing clinical records are never deleted. Offline grants can continue until their allowance ends.','Confirm');}
function addCustomer(){const manual=document.querySelector('meta[name=patholy-customer-portal]')?.content==='false';openForm('Add customer',[{name:'displayName',label:'Lab / customer name'},{name:'email',label:manual?'Customer contact email':'Customer identity email',type:'email'}],data=>api('customers/create',data),manual?'The owner issues activation keys and delivers them directly. No customer sign-in or password is required.':'Optional customer portal access uses an external identity provider. No customer password is created or stored here.');}
function invite(c){openForm('Invite '+c.display_name,[{name:'expiresAt',label:'Invitation expires',type:'datetime-local',help:'The invitation must be redeemed once by this customer’s verified identity.'}],data=>api('customers/invite',{customerId:c.id,expiresAt:Math.floor(new Date(data.expiresAt).getTime()/1000)}),'Send the one-time token securely to '+c.email+'. The licensing service does not send email automatically.','Create invitation');}
function policy(existing){const selectedCustomerId=state.customerId;if(!existing&&!state.customerId){feedback('Choose a customer before creating a licence.',true);return;}const fields=[];if(!existing)fields.push({name:'kind',label:'Type',options:[['','Choose licence or trial'],['licence','Licence'],['trial','Seven-day trial']]});fields.push({name:'expiresAt',label:'Expires',type:'datetime-local',required:!!existing,value:existing&&existing.expires_at?localDate(existing.expires_at):undefined,help:'Paid expiry is required. A new trial starts its seven days on the first successful online activation.'},{name:'seats',label:'Device seats',type:'number',min:1,max:10000,step:1,value:existing?.seats},{name:'offlineSeconds',label:'Offline allowance (seconds)',type:'number',min:1,max:2592000,step:1,value:existing?.offline_seconds,help:'Maximum 30 days, capped by expiry. Choose explicitly; offline revocation may take this long.'});openForm(existing?'Extend licence / change policy':'Create licence or trial',fields,data=>{const trial=!existing&&data.kind==='trial';if(!trial&&!data.expiresAt)throw Error('Choose the paid licence expiry.');return api('licenses/'+(existing?'renew':'create'),{...(existing?{licenseId:existing.id}:{customerId:selectedCustomerId,kind:data.kind}),...(!trial?{expiresAt:Math.floor(new Date(data.expiresAt).getTime()/1000)}:{}),seats:Number(data.seats),offlineSeconds:Number(data.offlineSeconds)});},existing?.kind==='trial'?'Trial extensions are explicit and audited; the original activation date remains unchanged. Activate a pending trial before extending.':'Trials start on first successful activation. Paid validity and device seats have no assumed defaults.');if(!existing){const kind=$('fields').querySelector('[name=kind]'),expiry=$('fields').querySelector('[name=expiresAt]');kind.addEventListener('change',()=>{expiry.disabled=kind.value==='trial';expiry.required=kind.value==='licence';});}}

async function devices(l){const customerId=state.customerId;openForm('Manage device seat',[{name:'activationId',label:'Active installation',options:[['','Loading active installations…']]},{name:'action',label:'Action',options:[['','Choose an action'],['reset','Reset / revoke this seat'],['transfer','Transfer to a new installation']]},{name:'deviceId',label:'New installation ID (for transfer)',required:false,help:'Copy the 64-character installation ID from the new app’s licence settings.'}],data=>{if(data.action==='transfer'&&!/^[a-f0-9]{64}$/.test(data.deviceId))throw new Error('Enter a 64-character installation ID.');return api('licenses/'+data.action,{licenseId:l.id,activationId:data.activationId,...(data.action==='transfer'?{deviceId:data.deviceId}:{})});},'Load additional active installations if your device is not on this page. Old offline grants remain usable until their allowance ends.','Confirm device change');const generation=++state.modalGeneration;let cursor=null,busy=false;const select=$('fields').querySelector('[name=activationId]');const more=action('Load more active installations',()=>fetchDevices(true));more.className='secondary';more.hidden=true;$('fields').append(more);$('submit').disabled=true;async function fetchDevices(append){if(busy)return;busy=true;more.disabled=true;try{const result=await api('devices/list',{customerId,licenseId:l.id,status:'active',...(append&&cursor?{cursor}:{})});if(generation!==state.modalGeneration||!$('editor').open)return;if(!append)select.replaceChildren(new Option('Choose an installation',''));for(const a of result.activations||[])if(![...select.options].some(o=>o.value===a.id))select.append(new Option(a.device_id,a.id));cursor=result.nextCursor||null;more.hidden=!cursor;$('submit').disabled=select.options.length<=1;if(select.options.length<=1){$('form-error').textContent='This licence has no active installations.';$('form-error').hidden=false;}}catch(e){if(generation===state.modalGeneration&&$('editor').open){$('submit').disabled=true;$('form-error').textContent=e.message;$('form-error').hidden=false;}}finally{busy=false;more.disabled=false;}}await fetchDevices(false);}
function showSecret(result){const value=result.key||(result.inviteToken?new URL('/invite',document.querySelector('meta[name=patholy-api-origin]')?.content||location.origin).href+'#token='+encodeURIComponent(result.inviteToken):'');if(!value)return;$('secret-title').textContent=result.key?'Licence key · shown once':'Invitation token · shown once';$('secret').value=value;$('copy-status').textContent='';$('secret-dialog').showModal();}
$('form').addEventListener('submit',async e=>{e.preventDefault();if(!state.submit)return;$('submit').disabled=true;$('form-error').hidden=true;try{const result=await state.submit(Object.fromEntries(new FormData($('form'))));closeForm();feedback('Change saved.');showSecret(result);await load();}catch(error){$('form-error').textContent=error.message;$('form-error').hidden=false;}finally{$('submit').disabled=false;}});
$('close').addEventListener('click',closeForm);$('cancel').addEventListener('click',closeForm);$('editor').addEventListener('cancel',()=>{state.modalGeneration++;state.submit=null;});$('create').addEventListener('click',()=>state.view==='customers'?addCustomer():policy());$('refresh').addEventListener('click',()=>{feedback('');load();});let searchTimer;$('search').addEventListener('input',e=>{state.query=e.target.value;if(state.view==='customers'){clearTimeout(searchTimer);searchTimer=setTimeout(load,300);}else render();});document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>changeView(b.dataset.view)));
function clearSecret(){$('secret').value='';$('copy-status').textContent='';}$('secret-dialog').addEventListener('close',clearSecret);$('secret-dialog').addEventListener('cancel',clearSecret);$('done-secret').addEventListener('click',()=>{$('secret-dialog').close();clearSecret();});$('copy-secret').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('secret').value);$('copy-status').textContent='Copied. Clear your clipboard after secure delivery.';}catch{$('copy-status').textContent='Select and copy the value manually.';}});load();

if(document.querySelector('meta[name=patholy-owner-auth]')?.content==='workos'){
 const area=node('div',undefined,'owner-session-actions');
 const security=node('a','Password & security');security.href='/owner/security';area.append(security);
 const logout=action('Log out',async()=>{logout.disabled=true;try{const r=await fetch('/v1/owner-auth/logout',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Patholy-Owner-Action':'1'},body:'{}',redirect:'error'});if(!r.ok)throw new Error('Logout could not be completed. Retry.');location.assign('/owner/login');}catch(e){feedback(e.message,true);logout.disabled=false;}});area.append(logout);document.querySelector('header').append(area);
}
