'use strict';
const EMAIL='iamrobiul94@gmail.com';
const $=id=>document.getElementById(id);
let token=new URLSearchParams(location.hash.slice(1)).get('token');
history.replaceState(null,'',location.pathname);
const setup=location.pathname==='/owner/setup',security=location.pathname==='/owner/security',recoveryPath=location.pathname==='/owner/recover',reconcilePath=location.pathname==='/owner/reconcile';
let stage='loading',busy=false,failures=0,secret='',epoch=0,operation=null,recoveryConfigured=false,cleanupPending=false;
function notice(message,error=false){$('notice').textContent=message;$('notice').className=error?'error':'';$('notice').hidden=!message;}
async function api(action,data={}){const response=await fetch('/v1/owner-auth/'+action,{method:'POST',credentials:'same-origin',redirect:'error',headers:{'Content-Type':'application/json','X-Patholy-Owner-Action':'1'},body:JSON.stringify(data)});let result;try{result=await response.json();}catch{throw new Error('Your request could not be completed. Reload this page and sign in again.');}if(!response.ok){const error=new Error(response.status===429?'Too many attempts. Wait before trying again.':'Verification could not be completed. Check your details or start sign-in again.');error.status=response.status;throw error;}return result;}
function field(name,label,type='text',options={}){const wrap=document.createElement('div');wrap.className='field';const caption=document.createElement('label');caption.htmlFor='field-'+name;caption.textContent=label;const input=document.createElement('input');input.id=caption.htmlFor;input.name=name;input.type=type;input.required=true;for(const [key,value]of Object.entries(options))input[key]=value;wrap.append(caption,input);$('fields').append(wrap);return input;}
function clearEnrollment(){secret='';$('totp-secret').value='';$('totp-secret').type='password';$('reveal').textContent='Show';$('enrollment').hidden=true;}
function render(next){epoch++;stage=next;$('fields').replaceChildren();clearEnrollment();$('submit').disabled=false;$('auth-form').hidden=false;$('restart').hidden=next==='login'||next==='setup';$('back-console').hidden=!security||next.startsWith('recovery')||next.startsWith('backup');$('backup-actions').hidden=!security||!(next==='password'||next==='readiness-pending'&&cleanupPending);$('manage-backup').textContent=cleanupPending?'Complete recovery cleanup':'Replace recovery authenticator';$('recovery').hidden=next==='setup'||next.startsWith('recovery');if(next==='login'){token=null;$('heading').textContent='Owner sign-in';$('step').textContent='STEP 1 / 2 · PASSWORD';$('description').textContent='Use your owner password. Authenticator verification is required before the console opens.';field('email','Owner email','email',{value:EMAIL,readOnly:true,autoComplete:'username'});field('password','Password','password',{autoComplete:'current-password',maxLength:256});$('submit').textContent='Continue to verification';}
 if(next==='setup'){$('heading').textContent='Set your owner password';$('step').textContent='SECURE ONE-TIME SETUP';$('description').textContent='Choose your password here, then enroll an authenticator. This setup link does not grant console access by itself.';field('email','Owner email','email',{value:EMAIL,readOnly:true,autoComplete:'username'});field('password','New password','password',{autoComplete:'new-password',minLength:12,maxLength:256});field('confirmation','Confirm new password','password',{autoComplete:'new-password',minLength:12,maxLength:256});$('submit').textContent='Set password & enroll MFA';if(!token||token.length<32||token.length>512){$('submit').disabled=true;notice('The setup link is missing or invalid. Ask the authenticated deployment administrator for a new one-time setup link.',true);}}
 if(next==='mfa'){$('heading').textContent='Verify your authenticator';$('step').textContent='STEP 2 / 2 · AUTHENTICATOR';$('description').textContent='Enter the current six-digit code from your authenticator app. This step cannot be skipped.';field('code','Authenticator code','text',{autoComplete:'one-time-code',inputMode:'numeric',pattern:'[0-9]{6}',maxLength:6,minLength:6});$('submit').textContent='Verify & open console';}
 if(next==='readiness-pending'){$('heading').textContent='Deployment verification required';$('step').textContent='OWNER AUTHENTICATION VERIFIED';$('description').textContent='Owner authentication verified. Live owner access is not enabled; deployment verification required.';$('auth-form').hidden=true;$('back-console').hidden=true;$('recovery').hidden=true;}
 if(next==='enroll'){$('heading').textContent='Set up your authenticator';$('step').textContent='MFA ENROLLMENT';$('description').textContent='Password verified. Continue enrollment, then verify an authenticator code before the console opens.';$('submit').textContent='Continue authenticator setup';}
 if(next==='password'){$('heading').textContent='Change owner password';$('step').textContent='SECURITY · REAUTHENTICATION';$('description').textContent='Confirm your current password and a fresh authenticator code. All sessions will be revoked after the change.';field('currentPassword','Current password','password',{autoComplete:'current-password',maxLength:256});field('newPassword','New password','password',{autoComplete:'new-password',minLength:12,maxLength:256});field('confirmation','Confirm new password','password',{autoComplete:'new-password',minLength:12,maxLength:256});field('code','Fresh authenticator code','text',{autoComplete:'one-time-code',inputMode:'numeric',pattern:'[0-9]{6}',maxLength:6,minLength:6});$('submit').textContent='Change password & sign out';}
 if(next==='backup-enroll'){$('heading').textContent='Set up independent recovery';$('step').textContent='REQUIRED OWNER SECURITY';$('description').textContent='Confirm your current password and a fresh primary authenticator code. Recovery setup must be verified before first owner-console access; every factor change requires a fresh sign-in.';field('currentPassword','Current password','password',{autoComplete:'current-password',maxLength:256});field('code','Primary authenticator code','text',{autoComplete:'one-time-code',inputMode:'numeric',pattern:'[0-9]{6}',maxLength:6,minLength:6});$('submit').textContent=recoveryConfigured?'Replace recovery authenticator':'Enroll recovery authenticator';}
 if(next==='backup-cleanup'){$('heading').textContent='Complete recovery cleanup';$('step').textContent='SECURITY · REAUTHENTICATION';$('description').textContent='Verify your current password and primary authenticator to retry removal of the previous recovery factor. No provider changes occur until you submit.';field('currentPassword','Current password','password',{autoComplete:'current-password',maxLength:256});field('code','Primary authenticator code','text',{autoComplete:'one-time-code',inputMode:'numeric',pattern:'[0-9]{6}',maxLength:6,minLength:6});$('submit').textContent='Verify & complete cleanup';}
 if(next==='backup-confirm'){$('heading').textContent='Verify recovery authenticator';$('step').textContent='INDEPENDENT FACTOR VERIFICATION';$('description').textContent='Add this different secret to an independent secure device, then enter its code. This factor cannot be used for normal owner sign-in.';field('code','Recovery authenticator code','text',{autoComplete:'one-time-code',inputMode:'numeric',pattern:'[0-9]{6}',maxLength:6,minLength:6});const label=document.createElement('label');label.className='checkbox-confirm';const input=document.createElement('input');input.type='checkbox';input.required=true;input.name='independent';label.append(input,document.createTextNode('I stored this recovery secret separately from my primary authenticator.'));$('fields').append(label);$('submit').textContent='Verify recovery factor & sign out';}
 if(next==='recovery'){$('heading').textContent='Repair primary authenticator';$('step').textContent='PRIVATE SCOPED RECOVERY';$('description').textContent='Use the current owner password and your pre-enrolled independent recovery authenticator. This maintenance link permits repair only; customer and licence data remain locked.';field('email','Owner email','email',{value:EMAIL,readOnly:true,autoComplete:'username'});field('password','Current owner password','password',{autoComplete:'current-password',maxLength:256});field('code','Independent recovery code','text',{autoComplete:'one-time-code',inputMode:'numeric',pattern:'[0-9]{6}',maxLength:6,minLength:6});$('submit').textContent='Verify recovery proofs';if(!validTicket()){notice('The private maintenance link is missing or invalid. Request a new link from the authenticated deployment administrator.',true);$('submit').disabled=true;}}
 if(next==='recovery-enroll'){$('heading').textContent='Replace primary authenticator';$('step').textContent='REPAIR SCOPE ONLY';$('description').textContent='Recovery proofs were accepted. Enter your current password again to authorize a fresh primary authenticator. This repair session cannot access customer or licence records.';field('password','Current owner password again','password',{autoComplete:'current-password',maxLength:256});$('submit').textContent='Continue primary replacement';}
 if(next==='recovery-confirm'){$('heading').textContent='Verify new primary authenticator';$('step').textContent='FINAL REPAIR VERIFICATION';$('description').textContent='Enter the code from the new primary authenticator. Prior local and provider sessions must be revoked before fresh owner sign-in.';field('code','New primary authenticator code','text',{autoComplete:'one-time-code',inputMode:'numeric',pattern:'[0-9]{6}',maxLength:6,minLength:6});$('submit').textContent='Verify new primary & sign out';}
 if(next==='reconcile'){$('heading').textContent='Finish verified provisioning';$('step').textContent='PRIVATE PROVISIONING RECONCILIATION';$('description').textContent='Use the password originally chosen for the deployment-owned provider account. This link cannot adopt an unrelated account or reset its password.';field('email','Owner email','email',{value:EMAIL,readOnly:true,autoComplete:'username'});field('password','Original chosen password','password',{autoComplete:'current-password',maxLength:256});$('submit').textContent='Resume verified provisioning';if(!validTicket()){$('submit').disabled=true;notice('A valid private provisioning reconciliation link is required.',true);}}
 if(next==='loading'){$('heading').textContent='Checking owner access…';$('auth-form').hidden=true;}}
function validTicket(){return typeof token==='string'&&token.length>=32&&token.length<=512;}
function displaySecret(result,next){if(result.stage!==next||typeof result.secret!=='string'||!/^[A-Z2-7]{16,128}$/i.test(result.secret))throw new Error('Authenticator enrollment could not be completed. Start sign-in again.');render(next);secret=result.secret;$('totp-secret').value=secret;$('enrollment').hidden=false;$('auth-form').before($('enrollment'));}
async function submitStage(current,data,request){const call=async(action,body={})=>{const expected=epoch,result=await api(action,body);if(operation!==request||expected!==epoch)return null;return result;};
 const provision=async(action,next)=>{const result=await call(action);if(result)displaySecret(result,next);};
 if(current==='setup'){if(data.password!==data.confirmation)throw new Error('Passwords do not match.');const result=await call('bootstrap',{token,password:data.password});if(!result)return;token=null;if(result.stage!=='enroll')throw new Error('Owner setup requires authenticator enrollment.');render('enroll');await provision('enroll','mfa');}
 else if(current==='login'){const result=await call('login',{email:EMAIL,password:data.password});if(!result)return;if(result.stage==='enroll'){render('enroll');await provision('enroll','mfa');}else if(result.stage==='mfa')render('mfa');else throw new Error('Authenticator verification is required. Start sign-in again.');}
 else if(current==='enroll')await provision('enroll','mfa');
 else if(current==='mfa'){const result=await call('totp',{code:data.code});if(!result)return;if(!result.authenticated)throw new Error('Authenticator verification is required.');clearEnrollment();location.assign(result.ownerReady===true&&!result.setupRequired?'/owner':'/owner/security');}
 else if(current==='password'){if(data.newPassword!==data.confirmation)throw new Error('Passwords do not match.');const result=await call('password',{currentPassword:data.currentPassword,newPassword:data.newPassword,code:data.code});if(!result)return;if(!result.reauthenticationRequired)throw new Error('Sign out and sign in again to confirm the password change.');render('login');notice('Password changed. All previous sessions were revoked. Sign in again and verify your authenticator.');}
 else if(current==='backup-enroll'){const result=await call('backup-enroll',{currentPassword:data.currentPassword,code:data.code});if(result)displaySecret(result,'backup-confirm');}
 else if(current==='backup-confirm'){const result=await call('backup-verify',{code:data.code});if(!result)return;if(!result.ok||!result.reauthenticationRequired)throw new Error('Fresh sign-in is required after recovery setup.');render('login');cleanupPending=result.cleanupPending===true;notice(cleanupPending?'New recovery authenticator verified. Previous recovery-factor cleanup is pending; sign in again and complete cleanup from Security.':'Recovery authenticator verified. Previous sessions were revoked. Sign in again with your primary authenticator.');}
 else if(current==='backup-cleanup'){const result=await call('backup-cleanup',{currentPassword:data.currentPassword,code:data.code});if(!result)return;if(!result.ok)throw new Error('Cleanup could not be confirmed. Sign in again and check Security.');cleanupPending=result.cleanupPending===true;render('login');notice(cleanupPending?'Recovery cleanup remains pending. Sign in again and retry from Security.':'Recovery cleanup completed. Sign in again with your primary authenticator.');}
 else if(current==='recovery'){const result=await call('recover',{token,password:data.password,code:data.code});if(!result)return;token=null;if(result.stage!=='recovery-enroll')throw new Error('Recovery cannot open the owner console. A scoped repair session is required.');render('recovery-enroll');}
 else if(current==='recovery-enroll'){let result;try{result=await call('recovery-enroll',{password:data.password});}finally{const input=$('fields').querySelector('[name=password]');if(stage==='recovery-enroll'&&input)input.value='';data.password='';}if(result)displaySecret(result,'recovery-confirm');}
 else if(current==='recovery-confirm'){const result=await call('recovery-verify',{code:data.code});if(!result)return;if(!result.ok||!result.reauthenticationRequired)throw new Error('Primary repair is incomplete. Owner data remains locked.');render('login');notice('Primary authenticator replaced and prior sessions revoked. Sign in again with your password and new primary authenticator.');}
 else if(current==='reconcile'){const result=await call('reconcile',{token,password:data.password});if(!result)return;token=null;if(result.stage==='enroll'){render('enroll');await provision('enroll','mfa');}else if(result.stage==='mfa')render('mfa');else throw new Error('Verified provisioning must continue through authenticator verification.');}
}
$('auth-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;busy=true;$('manage-backup').disabled=true;const request=Symbol('owner-auth');operation=request;$('submit').disabled=true;notice('');const current=stage,data=Object.fromEntries(new FormData(event.currentTarget));try{await submitStage(current,data,request);}catch(error){if(operation!==request)return;if(['mfa','backup-confirm','recovery-confirm'].includes(current)&&error.status===401){failures++;const input=$('fields').querySelector('[name=code]');if(input)input.value='';if(failures>=5){render('login');notice('Verification could not be completed. Start sign-in again.',true);return;}}notice(error.message,true);}finally{for(const key of Object.keys(data))data[key]='';if(operation===request){operation=null;busy=false;$('manage-backup').disabled=false;$('submit').disabled=['setup','recovery','reconcile'].includes(stage)&&!validTicket();}}});
$('restart').addEventListener('click',async()=>{const request=Symbol('restart');operation=request;epoch++;busy=true;token=null;clearEnrollment();$('fields').replaceChildren();$('submit').disabled=true;try{await api('logout');if(operation!==request)return;failures=0;render('login');notice('');}catch(error){if(operation===request){render('login');notice('Sign-out could not be confirmed. Reload and sign in again; server-side operations may have completed.',true);}}finally{if(operation===request){operation=null;busy=false;}}});
$('manage-backup').addEventListener('click',()=>{operation=null;busy=false;render(cleanupPending?'backup-cleanup':'backup-enroll');notice('');});
$('reveal').addEventListener('click',()=>{const visible=$('totp-secret').type==='text';$('totp-secret').type=visible?'password':'text';$('reveal').textContent=visible?'Show':'Hide';});$('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(secret);notice('Setup secret copied. Clear your clipboard after adding your authenticator.');}catch{notice('Select the setup secret and copy it manually.');}});
$('recovery').addEventListener('click',()=>{$('recovery-dialog').showModal();});$('close-recovery').addEventListener('click',()=>{$('recovery-dialog').close();$('recovery').focus();});$('recovery-dialog').addEventListener('close',()=>$('recovery').focus());$('recovery-dialog').addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();$('close-recovery').focus();}});
(async()=>{if(setup){render('setup');return;}if(recoveryPath){render('recovery');return;}if(reconcilePath){render('loading');if(!validTicket()){render('reconcile');return;}const expected=epoch;try{const result=await api('reconcile-info',{token});if(epoch!==expected)return;if(result.purpose==='primary-recovery')render('recovery');else if(result.purpose==='provision-reconcile')render('reconcile');else throw new Error('Maintenance link purpose is not supported.');}catch(error){if(epoch===expected){render('reconcile');notice(error.message,true);$('submit').disabled=true;}}return;}render('loading');const expected=epoch;try{const result=await api('status');if(epoch!==expected)return;if(result.authenticated){recoveryConfigured=result.recoveryConfigured===true;cleanupPending=result.backupCleanupPending===true;if(result.recoveryConfigured===true&&result.ownerReady!==true){render('readiness-pending');}else if(result.ownerReady!==true||result.recoveryConfigured!==true){if(security)render('backup-enroll');else location.assign('/owner/security');}else if(security)render('password');else location.assign('/owner');return;}}catch{}if(epoch===expected)render('login');})();
